-- =========================
-- EXTENSIONS
-- =========================
create extension if not exists pgcrypto;

-- =========================
-- CATEGORIES
-- =========================
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- GUIDELINES (simplified core)
-- =========================
CREATE TABLE guidelines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- GUIDELINE SECTIONS (Markdown content blocks)
-- =========================
CREATE TABLE guideline_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guideline_id BIGINT REFERENCES guidelines(id) ON DELETE CASCADE,
  section_type TEXT NOT NULL,          -- e.g. 'overview', 'diagnosis' ...
  title TEXT DEFAULT '',               -- optional display title
  content TEXT DEFAULT '',             -- Markdown content
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- BOOKMARKS (unchanged)
-- =========================
CREATE TABLE bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guideline_id BIGINT REFERENCES guidelines(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(guideline_id)
);

-- =========================
-- INDEXES
-- =========================
CREATE INDEX idx_guidelines_category ON guidelines(category_id);
CREATE INDEX idx_guidelines_slug ON guidelines(slug);
CREATE INDEX idx_sections_guideline ON guideline_sections(guideline_id);
CREATE INDEX idx_sections_type ON guideline_sections(section_type);
CREATE INDEX idx_bookmarks_guideline ON bookmarks(guideline_id);

-- =========================
-- AUTO UPDATED_AT TRIGGER
-- =========================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_categories_updated
BEFORE UPDATE ON categories
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_guidelines_updated
BEFORE UPDATE ON guidelines
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_sections_updated
BEFORE UPDATE ON guideline_sections
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =========================
-- RLS ENABLE
-- =========================
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE guidelines ENABLE ROW LEVEL SECURITY;
ALTER TABLE guideline_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookmarks ENABLE ROW LEVEL SECURITY;

-- =========================
-- POLICIES
-- =========================
-- PUBLIC READ (Flutter app)
CREATE POLICY "Public read categories"
ON categories FOR SELECT USING (true);

CREATE POLICY "Public read guidelines"
ON guidelines FOR SELECT USING (true);

CREATE POLICY "Public read sections"
ON guideline_sections FOR SELECT USING (true);

-- BOOKMARKS (auth only)
CREATE POLICY "Auth manage bookmarks"
ON bookmarks
FOR ALL USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- ADMIN WRITE ACCESS (authenticated users)
CREATE POLICY "Admin manage categories"
ON categories
FOR ALL USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin manage guidelines"
ON guidelines
FOR ALL USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin manage sections"
ON guideline_sections
FOR ALL USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');
