-- =========================
-- GUIDELINE VERSIONS
-- =========================
CREATE TABLE guideline_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guideline_id BIGINT REFERENCES guidelines(id) ON DELETE CASCADE,
  version_number INT NOT NULL,
  title TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  sections JSONB NOT NULL DEFAULT '[]'::jsonb,   -- full snapshot of sections
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_versions_guideline ON guideline_versions(guideline_id);

-- =========================
-- IMAGES TABLE (metadata)
-- =========================
CREATE TABLE images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  public_url TEXT NOT NULL,
  uploaded_by UUID REFERENCES auth.users(id),
  guideline_id BIGINT REFERENCES guidelines(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- RLS FOR NEW TABLES
-- =========================
ALTER TABLE guideline_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE images ENABLE ROW LEVEL SECURITY;

-- Anyone authenticated can read versions (or public if you prefer)
CREATE POLICY "Authenticated can read versions"
ON guideline_versions FOR SELECT
USING (auth.role() = 'authenticated');

-- Only authenticated can insert versions (admin/contributor)
CREATE POLICY "Authenticated can insert versions"
ON guideline_versions FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

-- Images: authenticated users can read
CREATE POLICY "Authenticated can read images"
ON images FOR SELECT
USING (auth.role() = 'authenticated');

-- Authenticated users can insert images
CREATE POLICY "Authenticated can insert images"
ON images FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

-- (Optional) delete own images
CREATE POLICY "Users can delete own images"
ON images FOR DELETE
USING (auth.uid() = uploaded_by);

-- =========================
-- STORAGE BUCKET & POLICIES
-- =========================
-- You must create the bucket via dashboard or SQL:
-- INSERT INTO storage.buckets (id, name, public) VALUES ('guideline-images', 'guideline-images', true);

-- Allow authenticated users to upload files
CREATE POLICY "Authenticated can upload images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'guideline-images');

-- Allow public read access to images
CREATE POLICY "Public can view images"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'guideline-images');
